-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 23:46:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbfootball
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfootball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfootball` DEFAULT CHARACTER SET utf8 ;
USE `dbfootball` ;

-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_community` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(200) NULL,
  `nickname` VARCHAR(100) NULL,
  `initials` VARCHAR(50) NULL,
  `logotype` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `id_community` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `FK_team_community_idx` (`id_community` ASC),
  CONSTRAINT `FK_team_community`
    FOREIGN KEY (`id_community`)
    REFERENCES `dbfootball`.`tbl_community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_stadium` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `address` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_competition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_competition` INT NULL,
  `name` VARCHAR(100) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_season_competition_idx` (`id_competition` ASC),
  CONSTRAINT `fk_season_competition`
    FOREIGN KEY (`id_competition`)
    REFERENCES `dbfootball`.`tbl_competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_classification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NULL,
  `id_team` INT NULL,
  `matches_played` INT NULL,
  `matches_win` INT NULL,
  `matches_tied` INT NULL,
  `matches_lost` INT NULL,
  `goals_favor` INT NULL,
  `goals_against` INT NULL,
  `goals_difference` INT NULL,
  `points` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classification_season_idx` (`id_season` ASC),
  INDEX `fk_classification_team_idx` (`id_team` ASC),
  CONSTRAINT `fk_classification_season`
    FOREIGN KEY (`id_season`)
    REFERENCES `dbfootball`.`tbl_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classification_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `name` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `date_birth` DATE NULL,
  `photo` VARCHAR(200) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  `height` DOUBLE NULL,
  `weight` DOUBLE NULL,
  `foot` VARCHAR(100) NULL,
  `position` INT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_player_position_idx` (`position` ASC),
  CONSTRAINT `fk_player_position`
    FOREIGN KEY (`position`)
    REFERENCES `dbfootball`.`tbl_position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_match` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NULL,
  `id_stadium` INT NULL,
  `id_team_local` INT NULL,
  `id_team_visitor` INT NULL,
  `match_date` DATE NULL,
  `match_hour` TIME NULL,
  `match_round` INT NULL,
  `goal_local` INT NULL,
  `goal_visitor` INT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_math_season_idx` (`id_season` ASC),
  INDEX `fk_match_team_local_idx` (`id_team_local` ASC),
  INDEX `fk_match_team_visitor_idx` (`id_team_visitor` ASC),
  INDEX `fk_match_stadium_idx` (`id_stadium` ASC),
  CONSTRAINT `fk_match_season`
    FOREIGN KEY (`id_season`)
    REFERENCES `dbfootball`.`tbl_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_team_local`
    FOREIGN KEY (`id_team_local`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_team_visitor`
    FOREIGN KEY (`id_team_visitor`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_stadium`
    FOREIGN KEY (`id_stadium`)
    REFERENCES `dbfootball`.`tbl_stadium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_referee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_referee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NULL,
  `password` VARCHAR(250) NULL,
  `state` INT NULL,
  `role` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NULL,
  `id_team` INT NULL,
  `id_player` INT NULL,
  `dorsal` VARCHAR(10) NULL,
  `nickname` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_team_idx` (`id_team` ASC),
  INDEX `fk_template_player_idx` (`id_player` ASC),
  INDEX `fk_template_season_idx` (`id_season` ASC),
  CONSTRAINT `fk_template_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_template_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dbfootball`.`tbl_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_template_season`
    FOREIGN KEY (`id_season`)
    REFERENCES `dbfootball`.`tbl_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_matchalignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_matchalignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  `id_team` INT NULL,
  `id_player` INT NULL,
  `id_position` INT NULL,
  `headline` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matchalignment_match_idx` (`id_match` ASC),
  INDEX `fk_matchalignment_team_idx` (`id_team` ASC),
  INDEX `fk_matchalignment_player_idx` (`id_player` ASC),
  INDEX `fk_matchalignment_position_idx` (`id_position` ASC),
  CONSTRAINT `fk_matchalignment_match`
    FOREIGN KEY (`id_match`)
    REFERENCES `dbfootball`.`tbl_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchalignment_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchalignment_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dbfootball`.`tbl_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchalignment_position`
    FOREIGN KEY (`id_position`)
    REFERENCES `dbfootball`.`tbl_position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_typeresult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_typeresult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_matchresult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_matchresult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  `id_team` INT NULL,
  `id_player` INT NULL,
  `id_typeresult` INT NULL,
  `match_minute` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matchresult_match_idx` (`id_match` ASC),
  INDEX `fk_matchresult_team_idx` (`id_team` ASC),
  INDEX `fk_matchresult_player_idx` (`id_player` ASC),
  INDEX `fk_matchresult_typeresult_idx` (`id_typeresult` ASC),
  CONSTRAINT `fk_matchresult_match`
    FOREIGN KEY (`id_match`)
    REFERENCES `dbfootball`.`tbl_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchresult_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchresult_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dbfootball`.`tbl_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchresult_typeresult`
    FOREIGN KEY (`id_typeresult`)
    REFERENCES `dbfootball`.`tbl_typeresult` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_refereebody`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_refereebody` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  `id_referee` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_refereebody_match_idx` (`id_match` ASC),
  INDEX `fk_refereebody_referee_idx` (`id_referee` ASC),
  CONSTRAINT `fk_refereebody_match`
    FOREIGN KEY (`id_match`)
    REFERENCES `dbfootball`.`tbl_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refereebody_referee`
    FOREIGN KEY (`id_referee`)
    REFERENCES `dbfootball`.`tbl_referee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_technical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_technical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_technicalbody`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_technicalbody` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NULL,
  `id_team` INT NULL,
  `id_technical` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_technicalbody_team_idx` (`id_team` ASC),
  INDEX `fk_technicalbody_season_idx` (`id_season` ASC),
  INDEX `fk_technicalbody_technical_idx` (`id_technical` ASC),
  CONSTRAINT `fk_technicalbody_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technicalbody_season`
    FOREIGN KEY (`id_season`)
    REFERENCES `dbfootball`.`tbl_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technicalbody_technical`
    FOREIGN KEY (`id_technical`)
    REFERENCES `dbfootball`.`tbl_technical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_seasonteam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_seasonteam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NOT NULL,
  `id_team` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seasonteam_season_idx` (`id_season` ASC),
  INDEX `fx_seasonteam_team_idx` (`id_team` ASC),
  UNIQUE INDEX `index_unique_seasonteam` (`id_season` ASC, `id_team` ASC),
  CONSTRAINT `fk_seasonteam_season`
    FOREIGN KEY (`id_season`)
    REFERENCES `dbfootball`.`tbl_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fx_seasonteam_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_board_match_idx` (`id_match` ASC),
  INDEX `FK_board_team_idx` (`id_team` ASC),
  CONSTRAINT `FK_board_match`
    FOREIGN KEY (`id_match`)
    REFERENCES `dbfootball`.`tbl_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_board_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `dbfootball`.`tbl_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfootball`.`tbl_communityplayer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfootball`.`tbl_communityplayer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_player` INT NULL,
  `id_community` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_communityplayer_player_idx` (`id_player` ASC),
  INDEX `FK_communityplayer_community_idx` (`id_community` ASC),
  CONSTRAINT `FK_communityplayer_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dbfootball`.`tbl_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_communityplayer_community`
    FOREIGN KEY (`id_community`)
    REFERENCES `dbfootball`.`tbl_community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
